@startuml
title 占い概念モデル

class 登録者
{
    -名前
    -パスワード
    -ポイント
}

class ゲスト

class 利用者登録
{
    -名前チェック
    -パスワードチェック
}

class 結果記録
{
    
}

class 占い結果
{
    -大中小凶
    -ラッキーアイテム
}

class 占い
{
    -大中小凶占い
    -ラッキーアイテム占い
}

class ポイント増減
{

}

ポイント増減 "1" -- "1" 占い
登録者 "1" -- "0..*" ポイント増減 
登録者 "1" -- "0..*" 結果記録
結果記録 "1" -- "1" 占い結果
結果記録 "1" -- "1" 占い
登録者 "1..*" -- "1" 利用者登録
占い "1" *-- "1" 占い結果
登録者 --|> ゲスト

@enduml